### ISSUE TITLE
hledger-interest fails to parse some journals

### ISSUE THREAD

**Issue by adept** [peti/hledger-interest#3]
Hi!

hledger-interest fails to parse some journals that hledger does not have any issues with, like this one:
```
commodity 1000.00 USD
```

Or this one:
```
2019-02-20 Reconciliation
  assets:a    = $100
   expenses:misc
```

Perhaps this is because it links against hledger-lib that is older than the one used by most recent hledger.

I appreciate that it might not be an easy change to make to update hledger-interest to hledger-lib 1.13.1 (and then keep it in sync). Would you be happy (or not opposed) for hledger-interest functionality to be merged into hledger itself?

**Comment by peti** [comment]
> Perhaps this is because it links against hledger-lib that is older than the one used by most recent hledger.

Yes, that is the only explanation because `hledger-interest` re-uses 100% of the parsing code from `hledger-lib`. So it's highly unlikely that `hledger` can parse constructs that `hledger-interest` can't. The current versions of `hledger-interest` works just fine with the latest `hledger-lib`, so I reckon that all you have to do to fix this issue is to re-build `hledger-interest`.

**Comment by adept** [comment]
Hmm. My version is built by stack using resolver lts-13.8, which includes
hledger-lib 1.13.1, yet somehow I ended with the binary that exhibits
behaviour I described. I will try and see which hledger - lib version it
got built against.

**Comment by adept** [comment]
I checked - my version of the binary is definitely built against hledger-lib-1.13.1.

**Comment by adept** [comment]
This is very embarassing, but I found an old binary lurking around that was shadowing the one that I thought I was using. Ignore me regarding unparseable files and sorry for the noise.

You haven't reacted in any way to my question about merging hledger-interest into hledger ... Shall I take it as "no"? :)

**Comment by peti** [comment]
> You haven't reacted in any way to my question about merging hledger-interest into hledger ... Shall I take it as "no"? :)

I doubt that Simon Michael would like the notion of building `hledger-interest` into `hledger` directly. That's not the direction he's taken with other tools. `hledger-ui`, `hledger-web`, etc. are all separate binaries (which `hledger` executes given the appropriate command). I don't see a strong rationale for making `hledger-interest` behave differently. Generally speaking, I also prefer a modular approach where tools that can be developed separately *are*  developed separately. Note that you can can build the latest version of `hledger-interest` against very old versions of `hledger-lib` if you want to. That would probably not be possible if it were integrated into the main distribution.

**Comment by peti** [comment]
I'm closing the ticket since the original problem has been resolved. :-)

**Comment by simonmichael** [comment]
Hi @peti. hledger-ui, hledger-web, hledger-api are separate because they have heavy additional dependencies and are/used to be harder/slower to install. Early on I thought it would be good to encourage other addons to be separate packages to scale better, but bundling things in the main package seems to provide a better user experience and reduce overall maintenance work (when dependencies aren't an issue). So that has been the recent trend. interest would fit well in hledger and I'd be glad to merge it if you're open to it. I suggested @adept inquire with you.

**Comment by peti** [comment]
> Early on I thought it would be good to encourage other addons to be separate packages to scale better, but bundling things in the main package seems to provide a better user experience and reduce overall maintenance work (when dependencies aren't an issue). So that has been the recent trend. interest would fit well in hledger and I'd be glad to merge it if you're open to it.

I have given this issue some thought. There are obvious advantages to be had by integrating `hledger-interest` into the main tool suite. It's probably the right choice from the user's point of view.

Personally, I'd prefer to keep it as a separate project, though. I like that approach because it encourages modularity and it maximizes my freedom in making design choices during development. I realize that approach comes with disadvantages (such as the issue we've witnessed in this very ticket), but all things considered I'd rather keep `hledger-interest` separate.

**Comment by simonmichael** [comment]
Fair enough, thanks.
